development:
    host: localhost
    adapter: postgresql
    encoding: unicode
    database: polygen-ror_development
    pool: 5
    username: polygen-ror
    password: polygen-ror

test:
    host: localhost
    adapter: postgresql
    encoding: unicode
    database: polygen-ror_test
    pool: 5
    username: polygen-ror
    password: polygen-ror
